### ISSUE TITLE
Deprecation of the Instagram Basic Display API.

### ISSUE THREAD

**Issue by shunmugakumaran** [wajahatbashir/InstagramFeeds#1]
Hi @wajahatbashir 

Facebook Meta has announced that it may deprecate the Instagram Basic Display API on December 4, 2024. Could you please confirm whether any code changes will be required on our end? If so, is there any possibility of a newer version being released from your side to accommodate these changes?

More reference : https://developers.facebook.com/docs/instagram-basic-display-api/

![image](https://github.com/user-attachments/assets/b1eb5178-dc94-4ad1-91c2-9589ed73a754)

**Comment by wajahatbashir** [comment]
You can update the API in the `WB\InstagramFeeds\Model` file. I’ll make sure to update it myself as soon as I have some time.

**Comment by shunmugakumaran** [comment]
@wajahatbashir  

Should be like this ? please confirm 

https://graph.instagram.com/v21.0/<ig_user_id>/media?access_token=<access_token>&fields=id%2Ccaption%2Cmedia_url%2Cpermalink%2Cmedia_type&limit=20
